### ISSUE TITLE
Need to change the location of files and folders

### ISSUE THREAD

**Issue by alexsuslov** [naueramant/go-3d-printer#1]
Please check my fork https://github.com/alexsuslov/go-3d-printer
this will allow using go-3d-printer as module
BRGD
Alex

**Comment by naueramant** [comment]
Thanks for the contribution Alex! 

I didn't really intend for anyone to use the package as it was only a side project I wanted to try out.

I will give your fork a look.

**Comment by naueramant** [comment]
I have updated the project structure to follow https://github.com/golang-standards/project-layout to allow for module use and cli use. Example:

```golang
package main

import (
	"context"

	"github.com/naueramant/go-3d-printer/pkg/factory"
)

func main() {
	p, err := factory.Connect(context.TODO(), "/dev/ttyUSB0")
	if err != nil {
		panic(err)
	}

	...
}

```
